//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testapp.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fenixklgEntities : DbContext
    {
        public fenixklgEntities()
            : base("name=fenixklgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblUserTypes> tblUserTypes { get; set; }
        public virtual DbSet<tblBalance> tblBalance { get; set; }
        public virtual DbSet<tblNews> tblNews { get; set; }
    }
}
