//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testapp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Nik { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual tblUserTypes tblUserTypes { get; set; }
    }
}
